# Generated by Django 6.0.7 on 2026-10-04 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_type', models.CharField(choices=[('livestock_inventory', 'Livestock Inventory'), ('production', 'Production Records'), ('disease', 'Disease Reports'), ('mortality', 'Mortality Records'), ('slaughter', 'Slaughter Records'), ('auction', 'Auction / Live Animal Sales')], help_text='Target municipal dataset domain for this batch import.', max_length=50)),
                ('file_name', models.CharField(help_text='Original uploaded filename (CSV or XLSX).', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the file was uploaded.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated (Previewed)'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partially Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('target_status', models.CharField(choices=[('APPROVED', 'Approved (Official Historical Data)'), ('PENDING', 'Pending (Requires SIBAT/MAO Field Verification)')], default='APPROVED', help_text='Workflow status assigned to imported records.', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0, help_text='Total rows found in the uploaded spreadsheet (excluding header).')),
                ('valid_rows', models.PositiveIntegerField(default=0, help_text='Number of rows that passed validation.')),
                ('imported_rows', models.PositiveIntegerField(default=0, help_text='Number of rows successfully inserted into production tables.')),
                ('skipped_rows', models.PositiveIntegerField(default=0, help_text='Number of duplicate or ignored rows skipped during import.')),
                ('error_rows', models.PositiveIntegerField(default=0, help_text='Number of rows rejected due to schema or validation errors.')),
                ('error_log', models.JSONField(blank=True, default=list, help_text='Structured log of row errors for downloadable audit reports.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the batch transaction completed.', null=True)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, help_text='Total processing duration in seconds.', max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional remarks or notes about the import batch.')),
                ('uploaded_by', models.ForeignKey(help_text='MAO or Admin user who performed the upload.', on_delete=django.db.models.deletion.PROTECT, related_name='data_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Import Batch',
                'verbose_name_plural': 'Data Import Batches',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
