"""Printable PDF and formatted workbook renderers for the shared report dataset."""

from io import BytesIO
from xml.sax.saxutils import escape

import openpyxl
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter


def excel_report(report):
    """Render the exact structured dataset used by the preview as an .xlsx workbook."""
    workbook = openpyxl.Workbook()
    sheet = workbook.active
    sheet.title = report["title"][:31]
    total_columns = max(1, len(report["columns"]))
    sheet.merge_cells(start_row=1, start_column=1, end_row=1, end_column=total_columns)
    sheet.cell(1, 1, "SMARTLIVESTOCK-BATANGAS").font = Font(size=15, bold=True, color="FFFFFF")
    sheet.cell(1, 1).fill = PatternFill("solid", fgColor="1E4D2B")
    sheet.merge_cells(start_row=2, start_column=1, end_row=2, end_column=total_columns)
    sheet.cell(2, 1, report["title"]).font = Font(size=13, bold=True, color="1E4D2B")
    sheet.append([f"Municipality: {report['municipality']}"])
    sheet.append([f"Reporting period: {report['period']['date_from']} to {report['period']['date_to']}"])
    sheet.append([f"Generated: {report['generated_at']}  |  Generated by: {report['generated_by']}"])
    sheet.append([])
    sheet.append(["SUMMARY"])
    sheet.cell(sheet.max_row, 1).font = Font(bold=True, color="1E4D2B")
    for key, value in report["summary"].items():
        if isinstance(value, dict):
            for label, amount in value.items():
                sheet.append([f"{key.replace('_', ' ').title()} · {label}", amount])
        else:
            sheet.append([key.replace("_", " ").title(), value])
    sheet.append([])
    sheet.append(["DETAILED RECORDS"])
    sheet.cell(sheet.max_row, 1).font = Font(bold=True, color="1E4D2B")
    sheet.append([column["label"] for column in report["columns"]])
    header_row = sheet.max_row
    for cell in sheet[header_row]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="1E4D2B")
        cell.alignment = Alignment(wrap_text=True)
    for row in report["rows"]:
        sheet.append([row.get(column["key"], "") for column in report["columns"]])
    sheet.freeze_panes = f"A{header_row + 1}"
    sheet.auto_filter.ref = f"A{header_row}:{get_column_letter(total_columns)}{sheet.max_row}"
    for index, column in enumerate(report["columns"], start=1):
        values = [column["label"]] + [str(row.get(column["key"], "")) for row in report["rows"][:200]]
        sheet.column_dimensions[get_column_letter(index)].width = min(36, max(13, max(map(len, values)) + 2))
    output = BytesIO()
    workbook.save(output)
    return output.getvalue()


def pdf_report(report):
    """Build a paginated, landscape PDF from report data rather than a UI screenshot."""
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.pagesizes import landscape, letter
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import LongTable, Paragraph, SimpleDocTemplate, Spacer, TableStyle

    output = BytesIO()
    doc = SimpleDocTemplate(output, pagesize=landscape(letter), rightMargin=0.45 * inch,
                            leftMargin=0.45 * inch, topMargin=0.55 * inch, bottomMargin=0.55 * inch)
    normal = ParagraphStyle("ReportCell", fontName="Helvetica", fontSize=7, leading=9, alignment=TA_LEFT)
    header = ParagraphStyle("ReportHeader", parent=normal, fontName="Helvetica-Bold", textColor=colors.white)
    summary_label = ParagraphStyle("SummaryLabel", parent=normal, fontName="Helvetica-Bold", textColor=colors.HexColor("#1E4D2B"))
    story = [Paragraph("SMARTLIVESTOCK-BATANGAS", ParagraphStyle("Brand", fontName="Helvetica-Bold", fontSize=14, textColor=colors.HexColor("#1E4D2B"))),
             Paragraph(escape(report["title"]), ParagraphStyle("Title", fontName="Helvetica-Bold", fontSize=12)),
             Paragraph(f"Municipality: {escape(report['municipality'])} &nbsp; | &nbsp; Reporting period: {report['period']['date_from']} to {report['period']['date_to']}", normal),
             Paragraph(f"Generated: {report['generated_at']} &nbsp; | &nbsp; Generated by: {escape(report['generated_by'])}", normal), Spacer(1, 10),
             Paragraph("Summary", ParagraphStyle("SummaryTitle", fontName="Helvetica-Bold", fontSize=10, textColor=colors.HexColor("#1E4D2B")))]
    summary_rows = []
    for key, value in report["summary"].items():
        entries = value.items() if isinstance(value, dict) else [(key, value)]
        summary_rows.extend([[Paragraph(escape(f"{key.replace('_', ' ').title()} · {label}" if isinstance(value, dict) else label.replace("_", " ").title()), summary_label),
                              Paragraph(escape(str(amount)), normal)] for label, amount in entries])
    if summary_rows:
        story.extend([LongTable(summary_rows, colWidths=[1.65 * inch, 3.3 * inch], repeatRows=0,
                                style=TableStyle([("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#E8F0EA")),
                                                  ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CBD5D0")),
                                                  ("VALIGN", (0, 0), (-1, -1), "TOP")])), Spacer(1, 12)])
    story.append(Paragraph("Detailed records", ParagraphStyle("DetailTitle", fontName="Helvetica-Bold", fontSize=10, textColor=colors.HexColor("#1E4D2B"))))
    table_data = [[Paragraph(escape(column["label"]), header) for column in report["columns"]]]
    for row in report["rows"]:
        table_data.append([Paragraph(escape(str(row.get(column["key"], "") if row.get(column["key"]) is not None else "")), normal)
                           for column in report["columns"]])
    if len(table_data) == 1:
        table_data.append([Paragraph("No approved records match this period and filter selection.", normal)] + [""] * (len(report["columns"]) - 1))
    widths = [doc.width / len(report["columns"])] * len(report["columns"])
    story.append(LongTable(table_data, colWidths=widths, repeatRows=1,
                           style=TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E4D2B")),
                                             ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CBD5D0")),
                                             ("VALIGN", (0, 0), (-1, -1), "TOP"),
                                             ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F8F6")]),
                                             ("LEFTPADDING", (0, 0), (-1, -1), 4), ("RIGHTPADDING", (0, 0), (-1, -1), 4)])))

    def footer(canvas, document):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#64748B"))
        canvas.drawString(doc.leftMargin, 0.28 * inch, "Municipal Agriculture Office · Padre Garcia, Batangas")
        canvas.drawRightString(doc.pagesize[0] - doc.rightMargin, 0.28 * inch, f"Page {document.page}")
        canvas.restoreState()

    doc.build(story, onFirstPage=footer, onLaterPages=footer)
    return output.getvalue()
