"""Printable PDF and formatted workbook renderers for the shared report dataset."""

from datetime import datetime
from io import BytesIO
from math import ceil
from xml.sax.saxutils import escape

import openpyxl
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter


def _format_metric(value):
    if isinstance(value, (int, float)):
        return f"{value:,.2f}".rstrip("0").rstrip(".") if not float(value).is_integer() else f"{value:,.0f}"
    return str(value)


def excel_report(report):
    """Render the exact structured dataset used by the preview as an .xlsx workbook."""
    workbook = openpyxl.Workbook()
    sheet = workbook.active
    sheet.title = report["title"][:31]
    total_columns = max(1, len(report["columns"]))
    sheet.merge_cells(start_row=1, start_column=1, end_row=1, end_column=total_columns)
    sheet.cell(1, 1, "SMARTLIVESTOCK-BATANGAS").font = Font(size=15, bold=True, color="FFFFFF")
    sheet.cell(1, 1).fill = PatternFill("solid", fgColor="1E4D2B")
    sheet.merge_cells(start_row=2, start_column=1, end_row=2, end_column=total_columns)
    sheet.cell(2, 1, report["title"]).font = Font(size=13, bold=True, color="1E4D2B")
    sheet.append([f"Municipality: {report['municipality']}"])
    sheet.append([f"{report.get('period_label', 'Reporting period')}: {report['period']['date_from']} to {report['period']['date_to']}"])
    active_filters = [f"{key.replace('_', ' ').title()}: {value}" for key, value in report.get("filters", {}).items() if value]
    sheet.append([f"Filters: {' · '.join(active_filters) if active_filters else 'None'}"])
    sheet.append([f"Data status: {report['analysis']['data_status']}"])
    sheet.append([f"Generated: {report['generated_at']}  |  Generated by: {report['generated_by']}"])
    sheet.append([])
    sheet.append(["SUMMARY"])
    sheet.cell(sheet.max_row, 1).font = Font(bold=True, color="1E4D2B")
    for key, value in report["summary"].items():
        if isinstance(value, dict):
            for label, amount in value.items():
                sheet.append([f"{key.replace('_', ' ').title()} · {label}", "Not recorded" if amount is None else amount])
        else:
            sheet.append([key.replace("_", " ").title(), value])
    sheet.append([])
    analysis = report["analysis"]
    sheet.append(["EXECUTIVE SUMMARY"])
    sheet.cell(sheet.max_row, 1).font = Font(bold=True, color="1E4D2B")
    sheet.append(["Metric", "Value", "Unit / context"])
    for cell in sheet[sheet.max_row]:
        cell.font = Font(bold=True, color="1E4D2B")
    for item in analysis["executive_summary"]:
        sheet.append([item["label"], item["value"], item.get("detail", "")])
    sheet.append([])
    sheet.append(["KEY FINDINGS"])
    sheet.cell(sheet.max_row, 1).font = Font(bold=True, color="1E4D2B")
    for finding in analysis["key_findings"] or ["No key findings can be supported by the selected records."]:
        sheet.append([finding])
    sheet.append([])
    sheet.append(["PREVIOUS-PERIOD COMPARISON"])
    sheet.cell(sheet.max_row, 1).font = Font(bold=True, color="1E4D2B")
    comparison = analysis["comparison"]
    if comparison["available"]:
        sheet.append([f"Previous period: {comparison['period']['date_from']} to {comparison['period']['date_to']}"])
        sheet.append(["Metric", "Current", "Previous", "Unit", "Change (%)"])
        for item in comparison["metrics"]:
            sheet.append([item["label"], item["current"], item["previous"], item["unit"], item["change_percent"]])
    else:
        sheet.append([comparison.get("unavailable_reason", "Previous-period comparison unavailable due to insufficient data.")])
    sheet.append([])
    sheet.append(["TOP RANKINGS"])
    sheet.cell(sheet.max_row, 1).font = Font(bold=True, color="1E4D2B")
    for ranking in analysis["rankings"]:
        sheet.append([ranking["title"]])
        for index, item in enumerate(ranking["items"], start=1):
            sheet.append([index, item["name"], item["value"], ranking["unit"]])
    sheet.append(["DATA COVERAGE", analysis["coverage_notice"]])
    sheet.append(["DATA & METHODOLOGY", analysis["methodology"]])
    sheet.append([])
    sheet.append(["DETAILED RECORDS"])
    sheet.cell(sheet.max_row, 1).font = Font(bold=True, color="1E4D2B")
    sheet.append([column["label"] for column in report["columns"]])
    header_row = sheet.max_row
    for cell in sheet[header_row]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="1E4D2B")
        cell.alignment = Alignment(wrap_text=True)
    for row in report["rows"]:
        sheet.append([row.get(column["key"], "") for column in report["columns"]])
    sheet.freeze_panes = f"A{header_row + 1}"
    sheet.auto_filter.ref = f"A{header_row}:{get_column_letter(total_columns)}{sheet.max_row}"
    for index, column in enumerate(report["columns"], start=1):
        values = [column["label"]] + [str(row.get(column["key"], "")) for row in report["rows"][:200]]
        sheet.column_dimensions[get_column_letter(index)].width = min(36, max(13, max(map(len, values)) + 2))
    output = BytesIO()
    workbook.save(output)
    return output.getvalue()


def _chart_rows(rows, label_key, value_key, *, count=False):
    """Aggregate only values already present in the authorized report rows."""
    totals = {}
    for row in rows:
        name = str(row.get(label_key) or "Unknown")
        totals[name] = totals.get(name, 0) + (1 if count else float(row.get(value_key) or 0))
    return sorted(totals.items(), key=lambda pair: pair[1], reverse=True)


def _monthly_rows(rows, value_key, *, count=False, date_key="record_date"):
    totals = {}
    for row in rows:
        month = str(row.get(date_key) or "")[:7]
        if len(month) != 7:
            continue
        totals[month] = totals.get(month, 0) + (1 if count else float(row.get(value_key) or 0))
    return sorted(totals.items())


def _monthly_distinct_rows(rows, date_key, identity_key):
    months = {}
    for index, row in enumerate(rows):
        month = str(row.get(date_key) or "")[:7]
        if len(month) == 7:
            months.setdefault(month, set()).add(str(row.get(identity_key) or f"row-{index}"))
    return [(month, len(identities)) for month, identities in sorted(months.items())]


def _monthly_axis_ticks(months, max_ticks=8):
    """Choose readable month labels while leaving every plotted observation intact."""
    if len(months) <= max_ticks:
        indices = range(len(months))
    else:
        # PDF pages have less horizontal space than the web chart. Keep every
        # point, but label a width-based subset and always retain the final month.
        interval = ceil((len(months) - 1) / (max_ticks - 1))
        indices = sorted(set(range(0, len(months), interval)) | {len(months) - 1})

    labels = {}
    for index in indices:
        try:
            labels[index] = datetime.strptime(months[index], "%Y-%m").strftime("%b %y")
        except ValueError:
            labels[index] = months[index]
    return labels


def _distinct_count_rows(rows, label_key, identity_key):
    groups = {}
    for index, row in enumerate(rows):
        name = str(row.get(label_key) or "Unknown")
        groups.setdefault(name, set()).add(str(row.get(identity_key) or f"row-{index}"))
    return sorted(((name, len(identities)) for name, identities in groups.items()), key=lambda pair: pair[1], reverse=True)


def _monthly_type_rows(rows):
    """Build per-type monthly series; callers pass rows sharing one physical unit."""
    months = {}
    types = set()
    for row in rows:
        month = str(row.get("record_date") or "")[:7]
        if len(month) != 7:
            continue
        production_type = str(row.get("production_type") or "Unknown")
        types.add(production_type)
        values = months.setdefault(month, {})
        values[production_type] = values.get(production_type, 0) + float(row.get("quantity") or 0)
    return sorted(types), [(month, values) for month, values in sorted(months.items())]


def _stacked_rows(rows, category_key, series_key, value_key):
    """Aggregate additive quantities into category-by-series rows for stacked bars."""
    categories = {}
    series = set()
    for row in rows:
        category = str(row.get(category_key) or "Unknown")
        name = str(row.get(series_key) or "Unknown")
        series.add(name)
        values = categories.setdefault(category, {})
        values[name] = values.get(name, 0) + float(row.get(value_key) or 0)
    return sorted(series), [{"name": name, "values": values} for name, values in sorted(categories.items())]


def _report_chart_specs(report):
    """Describe the preview's charts from its already-filtered rows, without another query."""
    rows = report["rows"]
    kind = report["report_type"]
    specs = []

    def add(title, chart_type, data, unit="", description=""):
        specs.append({"title": title, "type": chart_type, "data": data, "unit": unit, "description": description})

    def bar(title, data, unit="", description=""):
        # Long category names are easier to read in a horizontal ranking.
        add(title, "bar", data, unit, description)

    def line(title, data, unit="", description=""):
        add(title, "line", data, unit, description)

    def pie(title, data, description=""):
        # A pie is meaningful for a small composition; larger category sets become rankings.
        add(title, "pie" if 2 <= len(data) <= 7 else "bar", data, "", description)

    def stacked(title, series, data, unit, description=""):
        specs.append({"title": title, "type": "stacked_bar", "data": data,
                      "series": series, "unit": unit, "description": description})

    if kind == "inventory":
        bar("Livestock by Barangay", _chart_rows(rows, "barangay", "quantity"), "heads", "Approved registered heads, ranked high to low.")
        pie("Livestock Distribution by Species", _chart_rows(rows, "species", "quantity"), "Share of registered livestock heads.")
        add("Historical Inventory Trend", "empty", [], description="No historical inventory trend available.")
        species, composition = _stacked_rows(rows, "barangay", "species", "quantity")
        stacked("Species Composition by Barangay", species, composition, "heads",
                "Stacked approved head counts show how livestock mix differs by barangay.")
    elif kind == "production":
        units = sorted({str(row.get("unit") or "Unknown") for row in rows})
        for unit in units:
            unit_rows = [row for row in rows if str(row.get("unit") or "Unknown") == unit]
            line(f"Production Over Time ({unit})", _monthly_rows(unit_rows, "quantity"), unit.lower(), "Monthly approved output.")
            distribution = _chart_rows(unit_rows, "production_type", "quantity")
            bar(f"Production by Type ({unit})", distribution, unit.lower(), "Production types compared only within the same unit.")
            if len(distribution) > 1:
                pie(f"Production Distribution by Type ({unit})", distribution, f"Share of production measured in {unit.lower()}; units remain separate.")
            bar(f"Production by Barangay ({unit})", _chart_rows(unit_rows, "barangay", "quantity"), unit.lower(),
                f"Recorded production volume by barangay, measured only in {unit.lower()}.")
            types, type_months = _monthly_type_rows(unit_rows)
            if len(types) > 1 and len(type_months) > 1:
                specs.append({"title": f"Production Type Trends ({unit})", "type": "multi_line",
                              "data": type_months, "series": types, "unit": unit.lower(),
                              "description": "Monthly output by type; only types recorded in this same unit share an axis."})
        bar("Number of Production Records by Barangay", _chart_rows(rows, "barangay", "", count=True), "records",
            "Counts approved submissions, not production volume.")
    elif kind == "disease_mortality":
        diseases = [row for row in rows if row.get("record_kind") == "DISEASE"]
        deaths = [row for row in rows if row.get("record_kind") == "MORTALITY"]
        line("Disease Cases Over Time", _monthly_rows(diseases, "affected_or_dead", count=True), "cases", "Descriptive approved disease case count by month.")
        pie("Disease Distribution", _chart_rows(diseases, "condition_or_cause", "affected_or_dead"), "Approved affected animals by reported condition.")
        pie("Disease Cases by Disease Type", _chart_rows(diseases, "condition_or_cause", "", count=True), "Approved case records by reported condition.")
        bar("Disease by Barangay", _chart_rows(diseases, "barangay", "affected_or_dead"), "affected", "Approved affected animals by barangay.")
        bar("Reported Disease Cases by Barangay", _chart_rows(diseases, "barangay", "", count=True), "cases",
            "Counts approved case records by barangay, distinct from affected animal totals.")
        line("Mortality Over Time", _monthly_rows(deaths, "affected_or_dead", count=True), "records", "Descriptive approved mortality records by month.")
        bar("Mortality by Species", _chart_rows(deaths, "species", "affected_or_dead"), "deaths", "Approved deaths by species.")
    elif kind == "slaughter":
        line("Slaughter Trend", _monthly_rows(rows, "quantity"), "animals", "Animals slaughtered per month.")
        species = _chart_rows(rows, "species", "quantity")
        bar("Slaughter by Species", species, "animals", "Approved animals slaughtered.")
        pie("Slaughtered Animals by Species", species, "Part-to-whole distribution of approved slaughter counts.")
        weights = _chart_rows([row for row in rows if row.get("carcass_weight_kg") is not None], "species", "carcass_weight_kg")
        bar("Carcass Weight by Species", weights, "kg", "Carcass kilograms are shown separately from animal counts.")
        bar("Slaughter by Barangay", _chart_rows([row for row in rows if row.get("barangay")], "barangay", "quantity"),
            "animals", "Approved slaughtered head counts grouped by the recorded slaughter barangay.")
        average_weights = {}
        for row in rows:
            if row.get("carcass_weight_kg") is None:
                continue
            name = str(row.get("species") or "Unknown")
            total, heads = average_weights.get(name, (0.0, 0.0))
            average_weights[name] = (total + float(row["carcass_weight_kg"]), heads + float(row.get("quantity") or 0))
        averages = sorted(((name, total / heads) for name, (total, heads) in average_weights.items() if heads),
                          key=lambda item: item[1], reverse=True)
        bar("Average Recorded Carcass Weight by Species", averages, "kg/head",
            "Weighted average kilograms per slaughtered head, using records with a recorded carcass weight.")
    elif kind == "movement":
        auction = [row for row in rows if row.get("record_kind") == "AUCTION"]
        movement = [row for row in rows if row.get("record_kind") == "MOVEMENT"]
        line("Auction Activity Over Time", _monthly_rows(auction, "quantity"), "heads", "Approved auction sale items processed per month.")
        line("Auction Records Over Time", _monthly_rows(auction, "", count=True), "records",
             "Counts auction sale records per month, separate from the number of animals processed.")
        pie("Auction Livestock by Species", _chart_rows(auction, "species", "quantity"), "Approved livestock sale quantity.")
        bar("Auction Origins", _chart_rows(auction, "origin", "quantity"), "heads", "Seller barangay from the linked farmer record.")
        bar("Auction Destinations", _chart_rows(auction, "destination", "quantity"), "heads", "Recorded sale destination.")
        bar("Auction Purpose", _chart_rows(auction, "purpose", "quantity"), "heads")
        directions = [(direction, sum(row.get("direction") == direction for row in movement))
                      for direction in ("INBOUND", "OUTBOUND", "INTERNAL", "UNKNOWN")]
        add("Movement Direction", "pie", directions, description="Direction uses the shared classifier; UNKNOWN locations are retained rather than guessed.")
        line("Movement Trend", _monthly_rows(movement, "quantity"), "heads", "Movement lines by inspection month.")
        line("Movement Records Over Time", _monthly_distinct_rows(movement, "record_date", "control_number"),
             "records", "Distinct approved movement control records by inspection month.")
        bar("Top Origins", _chart_rows(movement, "origin", "quantity"), "heads")
        bar("Top Destinations", _chart_rows(movement, "destination", "quantity"), "heads")
        bar("Movement Purpose", _chart_rows(movement, "purpose", "quantity"), "heads")
        bar("Movement by Species", _chart_rows(movement, "species", "quantity"), "heads")
    elif kind == "inspection":
        pie("Inspection Status", _distinct_count_rows(rows, "clearance_status", "control_number"), "Only statuses present in the approved report rows are shown.")
        line("Inspections Over Time", _monthly_distinct_rows(rows, "record_date", "control_number"), "inspections", "Distinct approved clearance records by inspection month.")
        bar("Inspection Purpose", _chart_rows(rows, "purpose", "quantity"), "heads")
        bar("Inspection Origins", _chart_rows(rows, "origin", "quantity"), "heads")
        bar("Inspection Destinations", _chart_rows(rows, "destination", "quantity"), "heads")
        clearance_rows = [row for row in rows if row.get("issued_date")]
        line("Clearance Trend", _monthly_distinct_rows(clearance_rows, "issued_date", "control_number"), "clearances", "Distinct approved clearances by issuance month.")
    return specs


def _report_chart_flowable(spec, width, height, colors):
    """Draw a lightweight vector chart so PDF charts stay sharp at any zoom."""
    from reportlab.platypus import Flowable

    class ReportChart(Flowable):
        def __init__(self):
            super().__init__()
            self.width, self.height = width, height

        def draw(self):
            canvas = self.canv
            chart_type = spec["type"]
            if chart_type in ("stacked_bar", "multi_line"):
                data = spec["data"]
            else:
                data = [(str(name), float(value)) for name, value in spec["data"] if float(value) >= 0]
            left, right, bottom, top = 150, self.width - 20, 28, self.height - 12
            if not data:
                canvas.setFont("Helvetica-Oblique", 9)
                canvas.setFillColor(colors.HexColor("#64748B"))
                canvas.drawCentredString(self.width / 2, self.height / 2, "No approved records are available for this chart within the selected period.")
                return
            if spec["type"] == "pie":
                total = sum(value for _, value in data)
                if total <= 0:
                    return
                cx, cy = self.width * 0.32, self.height * 0.51
                radius = min(self.height * 0.39, self.width * 0.2)
                start = 90
                for index, (name, value) in enumerate(data):
                    extent = 360 * value / total
                    if extent > 0:
                        canvas.setFillColor(colors.HexColor(("#047857", "#0EA5E9", "#F59E0B", "#8B5CF6", "#EF4444", "#14B8A6", "#64748B")[index % 7]))
                        canvas.wedge(cx - radius, cy - radius, cx + radius, cy + radius, startAng=start, extent=extent, fill=1, stroke=0)
                    start += extent
                canvas.setFont("Helvetica", 8)
                legend_x, legend_y = self.width * 0.58, self.height - 28
                for index, (name, value) in enumerate(data):
                    y = legend_y - index * 16
                    canvas.setFillColor(colors.HexColor(("#047857", "#0EA5E9", "#F59E0B", "#8B5CF6", "#EF4444", "#14B8A6", "#64748B")[index % 7]))
                    canvas.rect(legend_x, y - 2, 8, 8, fill=1, stroke=0)
                    canvas.setFillColor(colors.HexColor("#334155"))
                    canvas.drawString(legend_x + 13, y, f"{name[:42]} · {value:,.0f} ({value / total:.1%})")
                return
            if chart_type == "multi_line":
                months = [str(month) for month, _ in data]
                series = spec.get("series", [])
                legend_rows = ceil(len(series) / 3)
                plot_top = top - (legend_rows * 10 + 5)  # Reserve a band for the series legend.
                observed_values = [float(values[name]) for _, values in data for name in series if name in values]
                max_value = max(observed_values, default=0) or 1
                plot_bottom = 40
                palette = ("#047857", "#0EA5E9", "#F59E0B", "#8B5CF6", "#EF4444", "#14B8A6", "#64748B")
                canvas.setFont("Helvetica", 7)
                canvas.setFillColor(colors.HexColor("#64748B"))
                canvas.drawString(5, top - 2, spec.get("unit", "Total"))
                canvas.drawRightString(left - 5, plot_bottom - 2, "0")
                canvas.drawRightString(left - 5, plot_top - 2, f"{max_value:,.0f}")
                canvas.setStrokeColor(colors.HexColor("#E2E8F0"))
                canvas.line(left, plot_bottom, right, plot_bottom)
                canvas.line(left, plot_top, right, plot_top)
                month_ticks = _monthly_axis_ticks(months)
                for index, month in enumerate(months):
                    x = left + (right - left) * (index / max(1, len(months) - 1))
                    if index in month_ticks:
                        canvas.setFillColor(colors.HexColor("#64748B"))
                        canvas.drawCentredString(x, 13, month_ticks[index])
                for series_index, name in enumerate(series):
                    color = colors.HexColor(palette[series_index % len(palette)])
                    points = []
                    for index, (_, values) in enumerate(data):
                        # A missing type/month is missing data, not a measured zero.
                        if name not in values:
                            points.append(None)
                            continue
                        value = float(values[name])
                        x = left + (right - left) * (index / max(1, len(data) - 1))
                        y = plot_bottom + (plot_top - plot_bottom) * value / max_value
                        points.append((x, y))
                    canvas.setStrokeColor(color)
                    canvas.setLineWidth(1.6)
                    for first, second in zip(points, points[1:]):
                        if first is not None and second is not None:
                            canvas.line(first[0], first[1], second[0], second[1])
                    canvas.setFillColor(color)
                    for point in points:
                        if point is not None:
                            canvas.circle(point[0], point[1], 2, fill=1, stroke=0)
                    legend_x = left + (series_index % 3) * ((right - left) / 3)
                    legend_y = top - 9 - (series_index // 3) * 10
                    canvas.setFillColor(color)
                    canvas.rect(legend_x, legend_y, 7, 5, fill=1, stroke=0)
                    canvas.setFillColor(colors.HexColor("#334155"))
                    canvas.setFont("Helvetica", 7)
                    canvas.drawString(legend_x + 10, legend_y - 1, name[:22])
                return
            if chart_type == "stacked_bar":
                series = spec.get("series", [])
                max_value = max((sum(float(item["values"].get(name, 0) or 0) for name in series) for item in data), default=0) or 1
                palette = ("#047857", "#0EA5E9", "#F59E0B", "#8B5CF6", "#EF4444", "#14B8A6", "#64748B")
                canvas.setFont("Helvetica", 7)
                canvas.setFillColor(colors.HexColor("#64748B"))
                canvas.drawString(5, top - 2, spec.get("unit", "Total"))
                row_height = min(17, (top - bottom) / max(1, len(data)))
                for index, item in enumerate(data):
                    y = top - (index + 1) * row_height + 3
                    canvas.setFillColor(colors.HexColor("#334155"))
                    canvas.drawRightString(left - 8, y + 2, str(item["name"])[:22])
                    x = left
                    for series_index, name in enumerate(series):
                        value = float(item["values"].get(name, 0) or 0)
                        segment_width = (right - left) * value / max_value
                        if segment_width > 0:
                            canvas.setFillColor(colors.HexColor(palette[series_index % len(palette)]))
                            canvas.rect(x, y, segment_width, max(4, row_height - 4), fill=1, stroke=0)
                        x += segment_width
                    canvas.setFillColor(colors.HexColor("#334155"))
                    total = sum(float(item["values"].get(name, 0) or 0) for name in series)
                    canvas.drawString(min(x + 4, right - 28), y + 2, f"{total:,.0f}")
                # Compact two-row legend keeps all species identifiable in a printable chart.
                legend_y = 8
                for index, name in enumerate(series):
                    x = left + (index % 4) * ((right - left) / 4)
                    y = legend_y + (index // 4) * 9
                    canvas.setFillColor(colors.HexColor(palette[index % len(palette)]))
                    canvas.rect(x, y, 7, 5, fill=1, stroke=0)
                    canvas.setFillColor(colors.HexColor("#334155"))
                    canvas.setFont("Helvetica", 6.5)
                    canvas.drawString(x + 10, y - 1, name[:20])
                return
            max_value = max((value for _, value in data), default=0) or 1
            canvas.setStrokeColor(colors.HexColor("#CBD5D0"))
            canvas.setFillColor(colors.HexColor("#334155"))
            canvas.setFont("Helvetica", 7)
            if spec["type"] == "line":
                points = []
                # Leave a dedicated label band beneath the plot so selected
                # month ticks fit without touching the next chart or description.
                plot_bottom = 40
                month_ticks = _monthly_axis_ticks([name for name, _ in data])
                canvas.setFont("Helvetica", 7)
                canvas.setFillColor(colors.HexColor("#64748B"))
                canvas.drawString(5, top - 2, spec.get("unit", "Total"))
                canvas.drawRightString(left - 5, plot_bottom - 2, "0")
                canvas.drawRightString(left - 5, top - 2, f"{max_value:,.0f}")
                canvas.setStrokeColor(colors.HexColor("#E2E8F0"))
                canvas.line(left, plot_bottom, right, plot_bottom)
                canvas.line(left, top, right, top)
                for index, (name, value) in enumerate(data):
                    x = left + (right - left) * (index / max(1, len(data) - 1))
                    y = plot_bottom + (top - plot_bottom) * value / max_value
                    points.append((x, y))
                    if index in month_ticks:
                        canvas.setStrokeColor(colors.HexColor("#94A3B8"))
                        canvas.line(x, plot_bottom, x, plot_bottom - 3)
                        canvas.setFillColor(colors.HexColor("#64748B"))
                        canvas.drawCentredString(x, 13, month_ticks[index])
                canvas.setStrokeColor(colors.HexColor("#047857")); canvas.setLineWidth(2)
                for first, second in zip(points, points[1:]):
                    canvas.line(first[0], first[1], second[0], second[1])
                canvas.setFillColor(colors.HexColor("#047857"))
                for x, y in points:
                    canvas.circle(x, y, 2.5, fill=1, stroke=0)
                canvas.setFillColor(colors.HexColor("#334155"))
            else:
                canvas.line(left, bottom - 4, left, top + 4)
                row_height = min(18, (top - bottom) / max(1, len(data)))
                for index, (name, value) in enumerate(data):
                    y = top - (index + 1) * row_height + 3
                    canvas.drawRightString(left - 8, y + 2, name[:22])
                    canvas.setFillColor(colors.HexColor("#047857"))
                    canvas.roundRect(left, y, (right - left) * value / max_value, max(4, row_height - 4), 2, fill=1, stroke=0)
                    bar_end = left + (right - left) * value / max_value
                    if bar_end > right - 34:
                        canvas.setFillColor(colors.white)
                        canvas.drawRightString(bar_end - 5, y + 2, f"{value:,.0f}")
                    else:
                        canvas.setFillColor(colors.HexColor("#334155"))
                        canvas.drawString(bar_end + 4, y + 2, f"{value:,.0f}")

    if spec["type"] == "stacked_bar":
        # Let longer barangay lists use more vertical space before pagination.
        height = max(height, min(230, 55 + len(spec["data"]) * 15))
    elif spec["type"] == "multi_line":
        height = max(height, min(220, 125 + ceil(len(spec.get("series", [])) / 3) * 11))
    return ReportChart()


def pdf_report(report):
    """Build a paginated, landscape PDF from report data rather than a UI screenshot."""
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.pagesizes import landscape, letter
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import CondPageBreak, LongTable, Paragraph, SimpleDocTemplate, Spacer, TableStyle

    output = BytesIO()
    doc = SimpleDocTemplate(output, pagesize=landscape(letter), rightMargin=0.45 * inch,
                            leftMargin=0.45 * inch, topMargin=0.55 * inch, bottomMargin=0.55 * inch)
    normal = ParagraphStyle("ReportCell", fontName="Helvetica", fontSize=7, leading=9, alignment=TA_LEFT)
    header = ParagraphStyle("ReportHeader", parent=normal, fontName="Helvetica-Bold", textColor=colors.white)
    summary_label = ParagraphStyle("SummaryLabel", parent=normal, fontName="Helvetica-Bold", textColor=colors.HexColor("#1E4D2B"))
    story = [Paragraph("SMARTLIVESTOCK-BATANGAS", ParagraphStyle("Brand", fontName="Helvetica-Bold", fontSize=14, textColor=colors.HexColor("#1E4D2B"))),
             Paragraph(escape(report["title"]), ParagraphStyle("Title", fontName="Helvetica-Bold", fontSize=12)),
             Paragraph(f"Municipality: {escape(report['municipality'])} &nbsp; | &nbsp; {escape(report.get('period_label', 'Reporting period'))}: {report['period']['date_from']} to {report['period']['date_to']}", normal),
             Paragraph(f"Generated: {report['generated_at']} &nbsp; | &nbsp; Generated by: {escape(report['generated_by'])} &nbsp; | &nbsp; Data status: {escape(report['analysis']['data_status'])}", normal)]
    active_filters = [(key.replace("_", " ").title(), value) for key, value in report.get("filters", {}).items() if value]
    if active_filters:
        story.extend([Paragraph("Filters: " + " · ".join(f"{escape(key)}: {escape(str(value))}" for key, value in active_filters), normal), Spacer(1, 6)])
    else:
        story.extend([Paragraph("Filters: None", normal), Spacer(1, 6)])
    analysis = report["analysis"]
    section_style = ParagraphStyle("SummaryTitle", fontName="Helvetica-Bold", fontSize=10, textColor=colors.HexColor("#1E4D2B"))
    story.append(Paragraph("Executive Summary", section_style))
    kpi_rows = [[Paragraph("Measure", header), Paragraph("Value", header), Paragraph("Unit / context", header)]]
    kpi_rows.extend([[Paragraph(escape(item["label"]), normal), Paragraph(escape(_format_metric(item["value"])), normal), Paragraph(escape(item.get("detail", "")), normal)]
                     for item in analysis["executive_summary"]])
    if len(kpi_rows) > 1:
        story.extend([LongTable(kpi_rows, colWidths=[2.2 * inch, 1.5 * inch, 2.7 * inch], repeatRows=1,
                                style=TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E4D2B")),
                                                  ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CBD5D0")),
                                                  ("VALIGN", (0, 0), (-1, -1), "TOP")])), Spacer(1, 6)])
    else:
        story.append(Paragraph("No summary measures are available for this selection.", normal))
    story.append(Paragraph("Report summary totals", ParagraphStyle("SummarySubTitle", fontName="Helvetica-Bold", fontSize=8, textColor=colors.HexColor("#475569"))))
    summary_rows = []
    for key, value in report["summary"].items():
        entries = value.items() if isinstance(value, dict) else [(key, value)]
        summary_rows.extend([[Paragraph(escape(f"{key.replace('_', ' ').title()} · {label}" if isinstance(value, dict) else label.replace("_", " ").title()), summary_label),
                              Paragraph(escape("Not recorded" if amount is None else str(amount)), normal)] for label, amount in entries])
    if summary_rows:
        story.extend([LongTable(summary_rows, colWidths=[1.65 * inch, 3.3 * inch], repeatRows=0,
                                style=TableStyle([("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#E8F0EA")),
                                                  ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CBD5D0")),
                                                  ("VALIGN", (0, 0), (-1, -1), "TOP")])), Spacer(1, 12)])
    story.append(Paragraph("Key Findings", section_style))
    if analysis["key_findings"]:
        story.extend(Paragraph("• " + escape(finding), normal) for finding in analysis["key_findings"])
    else:
        story.append(Paragraph("There is not enough approved data in this selection to identify a key finding.", normal))
    story.extend([Spacer(1, 7), Paragraph("Previous-Period Comparison", section_style)])
    comparison = analysis["comparison"]
    if comparison["available"]:
        previous_period = comparison["period"]
        story.append(Paragraph(f"Previous period: {previous_period['date_from']} to {previous_period['date_to']} (same duration as the current period).", normal))
        compare_rows = [[Paragraph(heading, header) for heading in ("Metric", "Current", "Previous", "Change")]]
        compare_rows.extend([[Paragraph(escape(item["label"]), normal),
                              Paragraph(f"{escape(_format_metric(item['current']))} {escape(item['unit'])}", normal),
                              Paragraph(f"{escape(_format_metric(item['previous']))} {escape(item['unit'])}", normal),
                              Paragraph(f"{item['change_percent']:+g}%", normal)] for item in comparison["metrics"]])
        story.append(LongTable(compare_rows, colWidths=[2.3 * inch, 2 * inch, 2 * inch, 1.4 * inch], repeatRows=1,
                               style=TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E4D2B")),
                                                 ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CBD5D0")),
                                                 ("VALIGN", (0, 0), (-1, -1), "TOP")])))
    else:
        story.append(Paragraph(escape(comparison.get("unavailable_reason", "Previous-period comparison unavailable due to insufficient data.")), normal))
    if analysis["rankings"]:
        story.extend([Spacer(1, 7), Paragraph("Top Rankings", section_style)])
        for ranking in analysis["rankings"]:
            story.append(Paragraph(escape(ranking["title"]), ParagraphStyle("RankingTitle", parent=normal, fontName="Helvetica-Bold")))
            ranking_rows = [[Paragraph("Rank", header), Paragraph("Category", header), Paragraph("Value", header)]]
            ranking_rows.extend([[str(index), Paragraph(escape(item["name"]), normal),
                                  Paragraph(f"{escape(_format_metric(item['value']))} {escape(ranking['unit'])}", normal)]
                                 for index, item in enumerate(ranking["items"], start=1)])
            story.append(LongTable(ranking_rows, colWidths=[0.6 * inch, 3.8 * inch, 2.3 * inch], repeatRows=1,
                                   style=TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E8F0EA")),
                                                     ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CBD5D0")),
                                                     ("VALIGN", (0, 0), (-1, -1), "TOP")])))
    story.extend([Spacer(1, 7), Paragraph("Data Coverage", section_style), Paragraph(escape(analysis["coverage_notice"]), normal), Spacer(1, 10)])
    # The exporter receives the exact backend-filtered rows used by the preview;
    # deriving charts here avoids a second query or a frontend-supplied dataset.
    story.extend([Paragraph("Charts &amp; Analysis", ParagraphStyle("ChartSection", fontName="Helvetica-Bold", fontSize=11, textColor=colors.HexColor("#1E4D2B"))), Spacer(1, 5)])
    interpretations = {
        "inventory": "This report summarizes approved livestock inventory in the selected period. Species and barangay charts show how recorded heads are distributed.",
        "production": "This report summarizes approved production records. Each chart keeps its original unit, so liters, kilograms, and pieces are not combined.",
        "disease_mortality": "This report describes approved disease and mortality records. Case counts and affected animals are distinct measures; the charts are descriptive, not predictive.",
        "slaughter": "This report summarizes approved slaughter activity and recorded carcass weights. Animal counts and kilograms are charted separately.",
        "movement": "Auction Activity describes sale operations; Movement Analysis describes geographic direction. These are separate records and measures.",
        "inspection": "This report summarizes approved inspection and clearance records. Statuses shown are only those present in the filtered dataset.",
    }
    story.extend([Paragraph(escape(interpretations.get(report["report_type"], "Charts are based on approved records matching the selected filters.")), normal), Spacer(1, 6)])
    section = None
    for spec in _report_chart_specs(report):
        chart_section = "Auction Activity" if spec["title"].startswith("Auction") else "Movement Analysis" if spec["title"].startswith("Movement") or spec["title"].startswith("Top ") else None
        if chart_section and chart_section != section:
            story.extend([Spacer(1, 5), Paragraph(escape(chart_section), ParagraphStyle("ChartSubsection", fontName="Helvetica-Bold", fontSize=9, textColor=colors.HexColor("#1E4D2B")))])
            section = chart_section
        title_style = ParagraphStyle("ChartTitle", fontName="Helvetica-Bold", fontSize=9, leading=11, textColor=colors.HexColor("#0F172A"))
        story.append(Paragraph(escape(spec["title"]), title_style))
        if spec["description"]:
            story.append(Paragraph(escape(spec["description"]), ParagraphStyle("ChartDescription", parent=normal, fontSize=7, textColor=colors.HexColor("#64748B"))))
        # The flowable draws vector primitives and scales to the printable width,
        # so charts remain sharp and flow naturally before the detailed table.
        story.extend([_report_chart_flowable(spec, doc.width, 150, colors), Spacer(1, 7)])
    story.append(CondPageBreak(1.8 * inch))
    story.append(Paragraph("Detailed records", ParagraphStyle("DetailTitle", fontName="Helvetica-Bold", fontSize=10, textColor=colors.HexColor("#1E4D2B"))))
    table_data = [[Paragraph(escape(column["label"]), header) for column in report["columns"]]]
    for row in report["rows"]:
        table_data.append([Paragraph(escape(str(row.get(column["key"], "") if row.get(column["key"]) is not None else "")), normal)
                           for column in report["columns"]])
    if len(table_data) == 1:
        table_data.append([Paragraph("No approved records match this period and filter selection.", normal)] + [""] * (len(report["columns"]) - 1))
    widths = [doc.width / len(report["columns"])] * len(report["columns"])
    story.append(LongTable(table_data, colWidths=widths, repeatRows=1,
                           style=TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E4D2B")),
                                             ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CBD5D0")),
                                             ("VALIGN", (0, 0), (-1, -1), "TOP"),
                                             ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F8F6")]),
                                             ("LEFTPADDING", (0, 0), (-1, -1), 4), ("RIGHTPADDING", (0, 0), (-1, -1), 4)])))
    story.extend([Spacer(1, 12), Paragraph("Data &amp; Methodology", section_style), Paragraph(escape(analysis["methodology"]), normal)])

    def footer(canvas, document):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#64748B"))
        canvas.drawString(doc.leftMargin, 0.28 * inch, "Municipal Agriculture Office · Padre Garcia, Batangas")
        canvas.drawRightString(doc.pagesize[0] - doc.rightMargin, 0.28 * inch, f"Page {document.page}")
        canvas.restoreState()

    doc.build(story, onFirstPage=footer, onLaterPages=footer)
    return output.getvalue()
