# Generated by Django 6.0.6 on 2026-06-27 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0004_livestockinventory_review_remarks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('affected_count', models.IntegerField(default=0)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'APPROVED'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_disease_case', to=settings.AUTH_USER_MODEL)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disease_cases', to='livestock.livestockinventory')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_disease_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MortalityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death_count', models.IntegerField(default=0)),
                ('cause', models.TextField()),
                ('record_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_mortality_records', to=settings.AUTH_USER_MODEL)),
                ('disease_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diseases.diseasecase')),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mortality_cases', to='livestock.livestockinventory')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_mortality_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
