# Generated by Django 6.0.7 on 2026-07-12 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diseases', '0001_initial'),
        ('livestock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasecase',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_disease_case', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='livestock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disease_cases', to='livestock.livestockinventory'),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_disease_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_mortality_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='livestock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mortality_cases', to='livestock.livestockinventory'),
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_mortality_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='source_disease_case',
            field=models.ForeignKey(blank=True, help_text='Optional disease case that caused these deaths.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortality_records', to='diseases.diseasecase'),
        ),
    ]
