# Generated by Django 6.0.6 on 2026-07-01 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mortalityrecord',
            name='disease_case',
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='source_disease_case',
            field=models.ForeignKey(blank=True, help_text='Optional disease case that caused these deaths.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortality_records', to='diseases.diseasecase'),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='mortalityrecord',
            name='death_count',
            field=models.PositiveIntegerField(),
        ),
    ]
