# Generated by Django 6.0.7 on 2026-09-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_alter_diseasecase_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasecase',
            name='inspector_photo',
            field=models.ImageField(blank=True, help_text='SIBAT on-site field verification photo.', null=True, upload_to='disease_inspection/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='photo',
            field=models.ImageField(blank=True, help_text='Farmer-submitted photo evidence of the illness.', null=True, upload_to='disease_evidence/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='inspector_photo',
            field=models.ImageField(blank=True, help_text='SIBAT on-site field verification photo.', null=True, upload_to='mortality_inspection/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='photo',
            field=models.ImageField(blank=True, help_text='Farmer-submitted photo evidence of the mortality.', null=True, upload_to='mortality_evidence/%Y/%m/'),
        ),
    ]
