# Generated by Django 6.0.7 on 2026-09-25 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0004_diseasecase_inspector_photo_diseasecase_photo_and_more'),
        ('livestock', '0009_livestockinventory_avatar_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasecase',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional link if disease outbreak affects an entire cohort batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_cases', to='livestock.livestockbatch'),
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional link if mortality is recorded for a cohort batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortality_records', to='livestock.livestockbatch'),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='livestock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disease_cases', to='livestock.livestockinventory'),
        ),
        migrations.AlterField(
            model_name='mortalityrecord',
            name='livestock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mortality_cases', to='livestock.livestockinventory'),
        ),
    ]
