# Generated by Django 6.0.7 on 2026-09-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0005_diseasecase_batch_mortalityrecord_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasecase',
            name='previous_remarks',
            field=models.TextField(blank=True, help_text='Preserved review remarks from the previous revision cycle.', null=True),
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='previous_remarks',
            field=models.TextField(blank=True, help_text='Preserved review remarks from the previous revision cycle.', null=True),
        ),
    ]
