# Generated by Django 6.0.7 on 2026-09-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0006_diseasecase_previous_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortalityrecord',
            name='inventory_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
