# Generated by Django 6.0.7 on 2026-09-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0007_mortalityrecord_inventory_reconciled_at'),
        ('livestock', '0013_alter_livestockinventory_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasecase',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional link if disease outbreak affects an entire herd.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_cases', to='livestock.livestockbatch'),
        ),
        migrations.AlterField(
            model_name='mortalityrecord',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional link if mortality is recorded for a herd.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mortality_records', to='livestock.livestockbatch'),
        ),
    ]
