"""
Django settings for smartlivestock project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from dotenv import load_dotenv
from pathlib import Path
from datetime import timedelta
import dj_database_url

# Load environment variables from .env file (DEBUG, SECRET_KEY, DATABASE_PASS)
load_dotenv()

sys_debug = os.environ.get("DEBUG")
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = sys_debug == "True" or sys_debug == "1"

# Production and local allowed hosts
ALLOWED_HOSTS: list[str] = [
    host.strip()
    for host in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Override default Django User model with our custom one in users/models.py
AUTH_USER_MODEL = "users.User"

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",  # JWT auth (access + refresh tokens)
    "phonenumber_field",  # Phone number validation
    # Custom Django apps (order doesn't matter for models, but kept consistent)
    "production",
    "movements",
    "users",
    "livestock",
    "diseases",
]

# DRF config: JWT is the only authentication method used
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES" : (
        "rest_framework.permissions.IsAuthenticated",
    )
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "smartlivestock.urls"

# CORS & CSRF configuration for local development and production
def _normalize_origin(origin: str) -> str:
    origin = origin.strip()
    if origin and not origin.startswith(("http://", "https://")):
        return f"https://{origin}"
    return origin

# Always allow local Next.js frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

cors_origins_env = os.environ.get("CORS_ALLOWED_ORIGINS")
if cors_origins_env:
    for orig in cors_origins_env.split(","):
        normalized = _normalize_origin(orig)
        if normalized and normalized not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(normalized)

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

csrf_trusted_env = os.environ.get("CSRF_TRUSTED_ORIGINS")
if csrf_trusted_env:
    for orig in csrf_trusted_env.split(","):
        normalized = _normalize_origin(orig)
        if normalized and normalized not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(normalized)

if RENDER_EXTERNAL_HOSTNAME:
    render_origin = f"https://{RENDER_EXTERNAL_HOSTNAME}"
    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_origin)

# JWT token configuration
# Access token = short-lived (30 min), Refresh token = long-lived (7 days)
# Refresh tokens rotate: each refresh invalidates the old refresh token
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "smartlivestock.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

LOCAL_DATABASE = {
    "ENGINE": "django.db.backends.postgresql",
    "NAME": os.environ.get("DATABASE_NAME", "smart_livestock"),
    "USER": os.environ.get("DATABASE_USER", "smart_livestock_user"),
    "PASSWORD": os.environ.get("DATABASE_PASS"),
    "HOST": os.environ.get("DATABASE_HOST", "localhost"),
    "PORT": os.environ.get("DATABASE_PORT", "5433"),
}

RENDER_DB_URL = os.environ.get("RENDER_DATABASE_URL") or os.environ.get("DATABASE_URL")

DATABASES = {
    "local": LOCAL_DATABASE,
}

if RENDER_DB_URL:
    DATABASES["render"] = dj_database_url.config(
        default=RENDER_DB_URL,
        conn_max_age=600,
        conn_health_checks=True,
    )

# Choose which database is active by default:
# - On Render cloud deployment, automatically defaults to 'render'.
# - Locally, defaults to 'local' unless USE_RENDER_DB=True is set in .env.
use_render_as_default = (
    os.environ.get("USE_RENDER_DB", "").lower() in ("true", "1")
    or bool(RENDER_EXTERNAL_HOSTNAME)
)

if use_render_as_default and "render" in DATABASES:
    DATABASES["default"] = DATABASES["render"]
else:
    DATABASES["default"] = DATABASES["local"]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

# Set timezone to Philippines (Padre Garcia, Batangas local time)
TIME_ZONE = "Asia/Manila"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
os.makedirs(STATIC_ROOT, exist_ok=True)

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
