# Generated by Django 6.0.7 on 2026-07-12 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='farmer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestockinventory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inventories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestockinventory',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='livestock.farmer'),
        ),
        migrations.AddField(
            model_name='livestockinventory',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_inventories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestockinventory',
            name='livestock_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='livestock.livestocktype'),
        ),
    ]
