# Generated by Django 6.0.6 on 2026-06-26 08:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_farmer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LivestockInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('BATCH', 'Batch')], default='BATCH', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('tag_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('breed', models.CharField(blank=True, default='', max_length=50)),
                ('sex', models.CharField(blank=True, default='', max_length=10)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('health_status', models.CharField(max_length=255)),
                ('last_vaccination_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=25)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inventories', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='livestock.farmer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_inventories', to=settings.AUTH_USER_MODEL)),
                ('livestock_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farmer_livestock_type', to='livestock.livestocktype')),
            ],
        ),
    ]
