# Generated by Django 6.0.7 on 2026-07-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_censussubmission_censussubmissionitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestockinventory',
            name='health_status',
        ),
    ]
