# Generated by Django 6.0.6 on 2026-06-26 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_livestocktype_livestockinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockinventory',
            name='review_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livestockinventory',
            name='breed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='livestockinventory',
            name='health_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='livestockinventory',
            name='last_vaccination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livestockinventory',
            name='livestock_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='livestock.livestocktype'),
        ),
        migrations.AlterField(
            model_name='livestockinventory',
            name='sex',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='livestockinventory',
            name='tag_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='livestocktype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
