# Generated by Django 6.0.7 on 2026-08-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_remove_livestockinventory_health_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='censussubmissionitem',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
