# Generated by Django 6.0.6 on 2026-07-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_livestockinventory_review_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='contact_no',
        ),
    ]
