# Generated by Django 6.0.7 on 2026-09-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0005_censussubmissionitem_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='censussubmission',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
