# Generated by Django 6.0.7 on 2026-09-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0006_censussubmission_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockinventory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=25),
        ),
    ]
