# Generated by Django 6.0.7 on 2026-09-25 04:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0008_alter_censussubmission_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockinventory',
            name='avatar_key',
            field=models.CharField(blank=True, default='', help_text="Selected preset avatar key (e.g., 'cattle-brahman', 'swine-native').", max_length=50),
        ),
        migrations.AddField(
            model_name='livestockinventory',
            name='photo',
            field=models.ImageField(blank=True, help_text='Animal photograph or digital passport portrait.', null=True, upload_to='livestock_photos/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='LivestockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=100)),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('housing_pen', models.CharField(blank=True, default='', max_length=100)),
                ('feed_type', models.CharField(blank=True, default='', max_length=100)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('target_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('HARVESTED', 'Harvested'), ('SOLD', 'Sold'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=25)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='livestock.farmer')),
                ('livestock_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='livestock.livestocktype')),
            ],
            options={
                'verbose_name': 'Livestock Batch',
                'verbose_name_plural': 'Livestock Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='livestockinventory',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional cohort/batch this individual animal belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='livestock.livestockbatch'),
        ),
    ]
