# Generated by Django 6.0.7 on 2026-09-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0009_livestockinventory_avatar_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockinventory',
            name='entry_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('BATCH', 'Batch')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='livestockinventory',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Always 1 for individual animal records.'),
        ),
    ]
