# Generated by Django 6.0.7 on 2026-09-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0010_alter_livestockinventory_entry_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockinventory',
            name='operational_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('DECEASED', 'Deceased'), ('SLAUGHTERED', 'Slaughtered'), ('MOVED_OUT', 'Moved Out')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='livestockinventory',
            name='operational_status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
