# Generated by Django 6.0.7 on 2026-09-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0011_livestockinventory_operational_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censussubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('SUBJECT_TO_REVISION', 'Subject to Revision')], default='VERIFIED', max_length=25),
        ),
    ]
