# Generated by Django 6.0.7 on 2026-09-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0012_alter_censussubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockinventory',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional herd this individual animal belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='livestock.livestockbatch'),
        ),
    ]
