# Generated by Django 6.0.7 on 2026-10-02 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0013_alter_livestockinventory_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='livestockinventory',
            constraint=models.CheckConstraint(condition=models.Q(batch__isnull=True) | models.Q(entry_type='INDIVIDUAL', quantity=1), name='herd_inventory_one_animal'),
        ),
        migrations.AddConstraint(
            model_name='livestockinventory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entry_type', 'INDIVIDUAL'), _negated=True), ('quantity', 1), _connector='OR'), name='individual_inventory_one_head'),
        ),
    ]
