# Generated by Django 6.0.7 on 2026-10-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0014_livestockinventory_individual_inventory_one_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='rsbsa_number',
            field=models.CharField(blank=True, default='', help_text='Registry System for Basic Sectors in Agriculture (RSBSA) registration number', max_length=50),
        ),
    ]
