# Generated by Django 6.0.7 on 2026-10-07 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0015_farmer_rsbsa_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='censussubmission',
            constraint=models.UniqueConstraint(fields=('barangay', 'report_year', 'report_quarter'), name='uniq_census_barangay_period'),
        ),
    ]
