# Generated by Django 6.0.7 on 2026-10-08 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0016_censussubmission_uniq_census_barangay_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockOwnershipTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_certificate_number', models.CharField(max_length=100, unique=True)),
                ('original_certificate_number', models.CharField(max_length=100)),
                ('transfer_date', models.DateField()),
                ('municipality', models.CharField(max_length=150)),
                ('province', models.CharField(max_length=150)),
                ('animal_description', models.TextField(blank=True)),
                ('sex_at_transfer', models.CharField(blank=True, max_length=10)),
                ('age_at_transfer', models.CharField(blank=True, max_length=50)),
                ('municipality_brand', models.CharField(blank=True, max_length=100)),
                ('owner_brand', models.CharField(blank=True, max_length=100)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('SUBJECT_TO_REVISION', 'Subject to Revision')], default='PENDING', max_length=25)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_livestock_transfers', to=settings.AUTH_USER_MODEL)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_transfers', to='livestock.livestockinventory')),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_livestock_transfers', to='livestock.farmer')),
                ('previous_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_livestock_transfers', to='livestock.farmer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_livestock_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transfer_date', '-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'VERIFIED'])), fields=('livestock',), name='one_open_ownership_transfer_per_animal')],
            },
        ),
    ]
