# Generated by Django 6.0.7 on 2026-10-08 03:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0017_livestockownershiptransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockownershiptransfer',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
