# Generated by Django 6.0.7 on 2026-10-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0018_alter_livestockownershiptransfer_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockbatch',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='livestock_batches/%Y/%m/'),
        ),
    ]
