# Generated by Django 6.0.7 on 2026-10-08 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_transfers_as_registered(apps, schema_editor):
    # Before external parties were supported every saved transfer referenced a Farmer.
    Transfer = apps.get_model("livestock", "LivestockOwnershipTransfer")
    Transfer.objects.using(schema_editor.connection.alias).update(owner_type="REGISTERED_FARMER")


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0019_livestockbatch_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockownershiptransfer',
            name='external_owner_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='livestockownershiptransfer',
            name='external_owner_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='livestockownershiptransfer',
            name='owner_type',
            field=models.CharField(choices=[('REGISTERED_FARMER', 'Registered Farmer'), ('EXTERNAL_INDIVIDUAL', 'External Individual'), ('COMPANY', 'Company'), ('TRADER', 'Trader'), ('OTHER', 'Other')], default='REGISTERED_FARMER', max_length=30),
        ),
        migrations.AlterField(
            model_name='livestockownershiptransfer',
            name='new_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_livestock_transfers', to='livestock.farmer'),
        ),
        migrations.RunPython(mark_existing_transfers_as_registered, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='livestockownershiptransfer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_owner_address', ''), ('external_owner_name', ''), ('new_owner__isnull', False), ('owner_type', 'REGISTERED_FARMER')), models.Q(('new_owner__isnull', True), ('owner_type__in', ['EXTERNAL_INDIVIDUAL', 'COMPANY', 'TRADER', 'OTHER']), models.Q(('external_owner_name', ''), _negated=True)), _connector='OR'), name='ownership_transfer_owner_matches_type'),
        ),
    ]
