# Generated by Django 6.0.7 on 2026-10-10 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0021_livestockinventory_birth_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockinventory',
            name='ownership_certificate_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livestockinventory',
            name='ownership_certificate_recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_livestock_ownership_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestockinventory',
            name='ownership_certificate_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='livestockinventory',
            constraint=models.UniqueConstraint(condition=models.Q(('ownership_certificate_number', ''), _negated=True), fields=('ownership_certificate_number',), name='uniq_livestock_cert_number'),
        ),
    ]
