# Generated by Django 6.0.7 on 2026-10-10 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0022_livestockinventory_ownership_certificate_issued_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockGateVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_session_id', models.UUIDField()),
                ('certificate_number_checked', models.CharField(blank=True, default='', max_length=100)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_verifications', to='livestock.livestockinventory')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livestock_gate_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['verified_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('gate_session_id', 'livestock'), name='uniq_gate_scan_per_session')],
            },
        ),
    ]
