# Generated by Django 6.0.7 on 2026-10-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0023_livestockgateverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockownershiptransfer',
            name='transfer_certificate_number',
            field=models.CharField(max_length=100),
        ),
    ]
