# Generated by Django 6.0.6 on 2026-07-03 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0004_livestockinventory_review_remarks_and_more'),
        ('production', '0003_delete_meatmovementrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockInpection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('purpose', models.CharField(choices=[('BREEDING', 'Breeding'), ('FATTENING', 'Fattening'), ('SLAUGHTER', 'Slaughter'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=100)),
                ('destination', models.CharField(max_length=255)),
                ('inspection_date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inspections', to=settings.AUTH_USER_MODEL)),
                ('livestock_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livestock.livestocktype')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockInpectionClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=100, unique=True)),
                ('date_issued', models.DateField()),
                ('time_issued', models.TimeField(auto_now_add=True)),
                ('shipper_name', models.CharField(max_length=255)),
                ('shipper_address', models.CharField(max_length=255)),
                ('origin', models.CharField(default='Padre Garcia, Batangas', max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('livestock_handler_license_no', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='movements.livestockinpection')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_clearances', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_clearances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeatMovementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(blank=True, help_text='Optional name of the destination buyer or establishment.', max_length=255)),
                ('meat_type', models.CharField(choices=[('BEEF', 'Beef'), ('CARABEEF', 'Carabeef'), ('GOAT', 'Goat'), ('PORK', 'Pork')], max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('movement_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_meat_movements', to=settings.AUTH_USER_MODEL)),
                ('destination_barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_meat', to='livestock.barangay')),
                ('origin_barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_meat', to='livestock.barangay')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_meat_movements', to=settings.AUTH_USER_MODEL)),
                ('slaughter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meat_movements', to='production.slaughterrecord')),
            ],
        ),
    ]
