# Generated by Django 6.0.7 on 2026-07-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_name', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('BREEDING', 'Breeding'), ('FATTENING', 'Fattening'), ('SLAUGHTER', 'Slaughter'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('inspection_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockInspectionClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=100, unique=True)),
                ('date_issued', models.DateField()),
                ('time_issued', models.TimeField()),
                ('shipper_address', models.CharField(max_length=255)),
                ('origin', models.CharField(default='Padre Garcia, Batangas', max_length=255)),
                ('vehicle_plate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('livestock_handler_license_no', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockInspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('MIXED', 'Mixed')], default='MIXED', max_length=10)),
                ('classification', models.CharField(choices=[('BREEDER', 'Breeder'), ('SLAUGHTER', 'Slaughter'), ('FATTENING', 'Fattening'), ('OTHER', 'Other')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeatMovementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(blank=True, help_text='Optional name of the destination buyer or establishment.', max_length=255)),
                ('meat_type', models.CharField(choices=[('BEEF', 'Beef'), ('CARABEEF', 'Carabeef'), ('GOAT', 'Goat'), ('PORK', 'Pork')], max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('movement_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
