# Generated by Django 6.0.7 on 2026-07-12 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0002_initial'),
        ('movements', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockinspection',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestockinspection',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='livestock.farmer'),
        ),
        migrations.AddField(
            model_name='livestockinspectionclearance',
            name='inspection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='clearance', to='movements.livestockinspection'),
        ),
        migrations.AddField(
            model_name='livestockinspectionclearance',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_clearances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestockinspectionclearance',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_clearances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestockinspectionitem',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='movements.livestockinspection'),
        ),
        migrations.AddField(
            model_name='livestockinspectionitem',
            name='livestock_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_items', to='livestock.livestocktype'),
        ),
        migrations.AddField(
            model_name='meatmovementrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_meat_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meatmovementrecord',
            name='destination_barangay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_meat', to='livestock.barangay'),
        ),
        migrations.AddField(
            model_name='meatmovementrecord',
            name='origin_barangay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_meat', to='livestock.barangay'),
        ),
        migrations.AddField(
            model_name='meatmovementrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_meat_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meatmovementrecord',
            name='slaughter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meat_movements', to='production.slaughterrecord'),
        ),
    ]
