# Generated by Django 6.0.6 on 2026-07-03 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_livestockinventory_review_remarks_and_more'),
        ('movements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestockinpectionclearance',
            name='inspection',
        ),
        migrations.RemoveField(
            model_name='livestockinpectionclearance',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='livestockinpectionclearance',
            name='reviewed_by',
        ),
        migrations.CreateModel(
            name='LivestockInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_name', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('BREEDING', 'Breeding'), ('FATTENING', 'Fattening'), ('SLAUGHTER', 'Slaughter'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('inspection_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inspections', to=settings.AUTH_USER_MODEL)),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='livestock.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockInspectionClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=100, unique=True)),
                ('date_issued', models.DateField()),
                ('time_issued', models.TimeField()),
                ('shipper_address', models.CharField(max_length=255)),
                ('origin', models.CharField(default='Padre Garcia, Batangas', max_length=255)),
                ('vehicle_plate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('livestock_handler_license_no', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='clearance', to='movements.livestockinspection')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_clearances', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_clearances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockInspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('MIXED', 'Mixed')], default='MIXED', max_length=10)),
                ('classification', models.CharField(choices=[('BREEDER', 'Breeder'), ('SLAUGHTER', 'Slaughter'), ('FATTENING', 'Fattening'), ('OTHER', 'Other')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='movements.livestockinspection')),
                ('livestock_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_items', to='livestock.livestocktype')),
            ],
        ),
        migrations.DeleteModel(
            name='LivestockInpection',
        ),
        migrations.DeleteModel(
            name='LivestockInpectionClearance',
        ),
    ]
