# Generated by Django 6.0.7 on 2026-09-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockinspectionclearance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('SUBJECT_TO_REVISION', 'Subject to Revision')], default='PENDING', max_length=25),
        ),
        migrations.AlterField(
            model_name='meatmovementrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('SUBJECT_TO_REVISION', 'Subject to Revision')], default='PENDING', max_length=25),
        ),
    ]
