# Generated by Django 6.0.7 on 2026-10-02 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0003_alter_livestockinspectionclearance_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockinspectionclearance',
            name='date_issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livestockinspectionclearance',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_clearances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livestockinspectionclearance',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='livestockinspectionclearance',
            name='time_issued',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meatmovementrecord',
            name='meat_type',
            field=models.CharField(choices=[('BEEF', 'Beef'), ('CARABEEF', 'Carabeef'), ('GOAT', 'Goat'), ('PORK', 'Pork'), ('CHICKEN', 'Chicken')], max_length=20),
        ),
    ]
