# Generated by Django 6.0.7 on 2026-10-02 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0014_livestockinventory_individual_inventory_one_head'),
        ('movements', '0004_alter_livestockinspectionclearance_date_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockinspectionitem',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspection_items', to='livestock.livestockinventory'),
        ),
    ]
