# Generated by Django 6.0.7 on 2026-10-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0005_livestockinspectionitem_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockinspection',
            name='purpose',
            field=models.CharField(choices=[('BREEDING', 'Breeding'), ('FATTENING', 'Fattening'), ('SLAUGHTER', 'Slaughter'), ('UNKNOWN', 'Unknown'), ('OTHER', 'Other Purpose')], default='UNKNOWN', max_length=20),
        ),
    ]
