"""One slaughter event, one production projection, exact animal transitions."""
from django.db import transaction
from django.utils import timezone
from rest_framework.exceptions import ValidationError
from livestock.models import LivestockInventory, LivestockBatch
from production.models import SlaughterRecord


def validate_animals(record, animals):
    source = record.livestock or record.batch
    if not animals or len({a.pk for a in animals}) != len(animals):
        raise ValidationError({"selected_animals": "Select distinct animals that were slaughtered."})
    for animal in animals:
        if animal.farmer_id != source.farmer_id or animal.livestock_type_id != source.livestock_type_id:
            raise ValidationError({"selected_animals": "Every selected animal must belong to your source farm and species."})
        if animal.status != "APPROVED" or animal.operational_status != "ACTIVE" or animal.quantity != 1:
            raise ValidationError({"selected_animals": "Select only approved, active individual animals with one head each."})
        herd = record.batch or (record.livestock.batch if record.livestock else None)
        if herd and (animal.batch_id != herd.pk or herd.status != LivestockBatch.StatusType.ACTIVE):
            raise ValidationError({"selected_animals": "Selected animals must belong to the active source herd."})
        if not herd and (len(animals) != 1 or animal.pk != record.livestock_id):
            raise ValidationError({"selected_animals": "An individual source must identify exactly that animal."})
    if record.livestock_id and record.livestock_id not in {a.pk for a in animals}:
        raise ValidationError({"selected_animals": "Include the selected source animal."})


def sync_slaughter(record, animals):
    """The existing production queue displays this event; it is not a second meat event."""
    validate_animals(record, animals)
    source = record.livestock or record.batch
    slaughter = record.slaughter if record.slaughter_id else SlaughterRecord(created_by=record.created_by)
    if slaughter.inventory_reconciled_at:
        raise ValidationError({"slaughter": "Approved slaughter cannot be edited."})
    slaughter.livestock = record.livestock
    slaughter.batch = record.batch or (record.livestock.batch if record.livestock else None)
    slaughter.livestock_type = source.livestock_type
    slaughter.barangay = source.farmer.barangay
    slaughter.quantity = len(animals)
    slaughter.carcass_weight = record.quantity
    slaughter.record_date = record.record_date
    slaughter.status = record.status
    slaughter.save()
    slaughter.selected_animals.set(animals)
    if not record.slaughter_id:
        record.slaughter = slaughter
        record.save(update_fields=["slaughter"])
    return slaughter


@transaction.atomic
def reconcile_approved_slaughter(slaughter):
    slaughter = SlaughterRecord.objects.select_for_update().get(pk=slaughter.pk)
    if slaughter.inventory_reconciled_at:
        return slaughter
    if slaughter.status != "APPROVED":
        raise ValidationError({"status": "Only MAO-approved slaughter can update inventory."})
    ids = list(slaughter.selected_animals.values_list("id", flat=True))
    # Stable lock order prevents concurrent sale/death/slaughter approvals using the same animal.
    animals = list(LivestockInventory.objects.select_for_update().filter(pk__in=ids).order_by("pk"))
    record = slaughter.production_output
    validate_animals(record, animals)
    if len(animals) != slaughter.quantity:
        raise ValidationError({"selected_animals": "Slaughter head count must match the selected animals."})
    changed_at = timezone.now()
    LivestockInventory.objects.filter(pk__in=ids).update(operational_status="SLAUGHTERED", operational_status_changed_at=changed_at)
    # Surviving herd members remain active; mortality is never generated by slaughter.
    if slaughter.batch_id:
        herd = LivestockBatch.objects.select_for_update().get(pk=slaughter.batch_id)
        if not herd.animals.filter(operational_status="ACTIVE").exists():
            herd.status = LivestockBatch.StatusType.HARVESTED
            herd.save(update_fields=["status", "updated_at"])
    slaughter.inventory_reconciled_at = changed_at
    slaughter.save(update_fields=["inventory_reconciled_at"])
    return slaughter
