# Generated by Django 6.0.7 on 2026-07-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveAnimalSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sale_method', models.CharField(choices=[('MATA-MATA', 'Mata-mata'), ('WEIGHING', 'Weighing'), ('OTHER', 'Other')], default='MATA-MATA', max_length=20)),
                ('total_live_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Optional combined weight of all animals sold.', max_digits=8, null=True)),
                ('price_per_head', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('destination', models.CharField(blank=True, help_text='Buyer or destination municipality.', max_length=255)),
                ('sale_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('purpose', models.CharField(choices=[('BREEDING', 'Breeding'), ('FATTENING', 'Fattening'), ('SLAUGHTER', 'Slaughter'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_type', models.CharField(choices=[('MILK', 'Milk'), ('EGGS', 'Eggs'), ('WOOL', 'Wool')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('LITERS', 'Liters'), ('PIECES', 'Pieces'), ('KILOGRAMS', 'Kilograms')], max_length=20)),
                ('record_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlaughterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('carcass_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Optional total meat produced in kilograms.', max_digits=8, null=True)),
                ('record_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
