# Generated by Django 6.0.6 on 2026-07-01 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0004_livestockinventory_review_remarks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveAnimalSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_live_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Optional combined weight of all animals sold.', max_digits=8, null=True)),
                ('price_per_head', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('destination', models.CharField(blank=True, help_text='Buyer or destination municipality.', max_length=255)),
                ('sale_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('purpose', models.CharField(choices=[('BREEDING', 'Breeding'), ('FATTENING', 'Fattening'), ('SLAUGHTER', 'Slaughter'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sale_records', to=settings.AUTH_USER_MODEL)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_animal_sales', to='livestock.livestockinventory')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_sale_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_type', models.CharField(choices=[('MILK', 'Milk'), ('EGGS', 'Eggs'), ('WOOL', 'Wool')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('LITERS', 'Liters'), ('PIECES', 'Pieces'), ('KILOGRAMS', 'Kilograms')], max_length=20)),
                ('record_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_production_records', to=settings.AUTH_USER_MODEL)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_records', to='livestock.livestockinventory')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_production_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlaughterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('carcass_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Optional total meat produced in kilograms.', max_digits=8, null=True)),
                ('record_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slaughter_records', to='livestock.barangay')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_slaughter_records', to=settings.AUTH_USER_MODEL)),
                ('livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slaughter_records', to='livestock.livestockinventory')),
                ('livestock_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slaughter_records', to='livestock.livestocktype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_slaughter_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeatMovementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(blank=True, help_text='Optional name of the destination buyer or establishment.', max_length=255)),
                ('meat_type', models.CharField(choices=[('BEEF', 'Beef'), ('CARABEEF', 'Carabeef'), ('GOAT', 'Goat'), ('PORK', 'Pork')], max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('movement_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_meat_movements', to=settings.AUTH_USER_MODEL)),
                ('destination_barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_meat', to='livestock.barangay')),
                ('origin_barangay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_meat', to='livestock.barangay')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_meat_movements', to=settings.AUTH_USER_MODEL)),
                ('slaughter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meat_movements', to='production.slaughterrecord')),
            ],
        ),
    ]
