# Generated by Django 6.0.6 on 2026-07-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveanimalsale',
            name='sale_method',
            field=models.CharField(choices=[('MATA-MATA', 'Mata-mata'), ('WEIGHING', 'Weighing'), ('OTHER', 'Other')], default='MATA-MATA', max_length=20),
        ),
    ]
