# Generated by Django 6.0.7 on 2026-07-12 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0002_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liveanimalsale',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sale_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liveanimalsale',
            name='livestock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_animal_sales', to='livestock.livestockinventory'),
        ),
        migrations.AddField(
            model_name='liveanimalsale',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_sale_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_production_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='livestock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_records', to='livestock.livestockinventory'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_production_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slaughterrecord',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slaughter_records', to='livestock.barangay'),
        ),
        migrations.AddField(
            model_name='slaughterrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_slaughter_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slaughterrecord',
            name='livestock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slaughter_records', to='livestock.livestockinventory'),
        ),
        migrations.AddField(
            model_name='slaughterrecord',
            name='livestock_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slaughter_records', to='livestock.livestocktype'),
        ),
        migrations.AddField(
            model_name='slaughterrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_slaughter_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
