# Generated by Django 6.0.7 on 2026-08-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterrecord',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
