# Generated by Django 6.0.6 on 2026-07-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_liveanimalsale_sale_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeatMovementRecord',
        ),
    ]
