# Generated by Django 6.0.7 on 2026-08-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_slaughterrecord_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slaughterrecord',
            name='notes',
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
