# Generated by Django 6.0.7 on 2026-09-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_remove_slaughterrecord_notes_productionrecord_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecord',
            name='production_type',
            field=models.CharField(choices=[('MILK', 'Milk'), ('MEAT', 'Meat'), ('EGGS', 'Eggs'), ('WOOL', 'Wool')], max_length=20),
        ),
    ]
