# Generated by Django 6.0.7 on 2026-09-20 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0007_alter_livestockinventory_status'),
        ('production', '0005_alter_productionrecord_production_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('FOR_SALE', 'Intended for Sale'), ('FOR_SLAUGHTER', 'Intended for Slaughter'), ('FOR_MOVEMENT', 'Farm Transfer / Movement'), ('NONE', 'Active in Herd')], default='FOR_SALE', max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('target_destination', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_dispositions', to=settings.AUTH_USER_MODEL)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='livestock.livestockinventory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalvingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calf_tag', models.CharField(blank=True, max_length=50)),
                ('calf_sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='FEMALE', max_length=10)),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Birth weight in kilograms.', max_digits=6, null=True)),
                ('sire_tag', models.CharField(blank=True, help_text='Father / sire bull tag or breed origin.', max_length=50)),
                ('calving_date', models.DateField()),
                ('breed', models.CharField(blank=True, max_length=50)),
                ('calving_ease', models.CharField(blank=True, default='Normal / Unassisted', max_length=50)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_calving_records', to=settings.AUTH_USER_MODEL)),
                ('dam', models.ForeignKey(help_text='Mother cow / dam.', on_delete=django.db.models.deletion.PROTECT, related_name='calving_records', to='livestock.livestockinventory')),
            ],
            options={
                'ordering': ['-calving_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Recorded weight in kilograms.', max_digits=6)),
                ('weighing_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_weight_records', to=settings.AUTH_USER_MODEL)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='livestock.livestockinventory')),
            ],
            options={
                'ordering': ['-weighing_date', '-created_at'],
            },
        ),
    ]
