# Generated by Django 6.0.7 on 2026-09-25 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0009_livestockinventory_avatar_key_and_more'),
        ('production', '0007_alter_liveanimalsale_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveanimalsale',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional link if animals are sold from a cohort batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_animal_sales', to='livestock.livestockbatch'),
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional link if production is recorded for an entire batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_records', to='livestock.livestockbatch'),
        ),
        migrations.AddField(
            model_name='slaughterrecord',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional link if slaughter is recorded for a cohort batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slaughter_records', to='livestock.livestockbatch'),
        ),
        migrations.AlterField(
            model_name='liveanimalsale',
            name='livestock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='live_animal_sales', to='livestock.livestockinventory'),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='livestock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_records', to='livestock.livestockinventory'),
        ),
    ]
