# Generated by Django 6.0.7 on 2026-09-27 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_liveanimalsale_batch_productionrecord_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calvingrecord',
            name='review_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='calvingrecord',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calvingrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_calving_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calvingrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('SUBJECT_TO_REVISION', 'Subject to Revision')], default='PENDING', max_length=25),
        ),
    ]
