# Generated by Django 6.0.7 on 2026-09-29 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0011_livestockinventory_operational_status_and_more'),
        ('production', '0009_calvingrecord_review_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calvingrecord',
            name='inventory_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calvingrecord',
            name='offspring_inventory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_calving_record', to='livestock.livestockinventory'),
        ),
        migrations.AddField(
            model_name='liveanimalsale',
            name='inventory_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
