# Generated by Django 6.0.7 on 2026-09-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0013_alter_livestockinventory_batch'),
        ('production', '0010_calvingrecord_inventory_reconciled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveanimalsale',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional link if animals are sold from a herd.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_animal_sales', to='livestock.livestockbatch'),
        ),
        migrations.AlterField(
            model_name='slaughterrecord',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Optional link if slaughter is recorded for a herd.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slaughter_records', to='livestock.livestockbatch'),
        ),
    ]
