# Generated by Django 6.0.7 on 2026-10-01 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0013_alter_livestockinventory_batch'),
        ('production', '0011_alter_liveanimalsale_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='valuation_snapshot',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='PSAReferencePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_id', models.CharField(max_length=100)),
                ('commodity', models.CharField(max_length=150)),
                ('product_basis', models.CharField(choices=[('MILK', 'Milk'), ('EGGS', 'Eggs'), ('CARCASS', 'Carcass/meat yield'), ('WOOL', 'Wool'), ('LIVEWEIGHT', 'Live animal weight (not meat yield)')], max_length=20)),
                ('unit', models.CharField(choices=[('LITERS', 'Liters'), ('PIECES', 'Pieces'), ('KILOGRAMS', 'Kilograms')], max_length=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('reference_period', models.CharField(max_length=100)),
                ('geographic_level', models.CharField(default='NATIONAL', max_length=50)),
                ('geography', models.CharField(default='Philippines', max_length=100)),
                ('source_url', models.URLField(max_length=500)),
                ('source_title', models.CharField(max_length=250)),
                ('source_table', models.CharField(max_length=100)),
                ('publication_status', models.CharField(default='Preliminary', max_length=50)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='positive_psa_price'), models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='valid_psa_period'), models.UniqueConstraint(fields=('commodity_id', 'period_start', 'period_end', 'revision', 'geographic_level', 'geography'), name='unique_psa_price_revision')],
            },
        ),
        migrations.CreateModel(
            name='PSACommodityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_type', models.CharField(choices=[('MILK', 'Milk'), ('MEAT', 'Meat'), ('EGGS', 'Eggs'), ('WOOL', 'Wool')], max_length=20)),
                ('unit', models.CharField(choices=[('LITERS', 'Liters'), ('PIECES', 'Pieces'), ('KILOGRAMS', 'Kilograms')], max_length=20)),
                ('commodity_id', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('livestock_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livestock.livestocktype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('livestock_type', 'production_type', 'unit'), name='unique_psa_product_mapping')],
            },
        ),
    ]
