# Generated by Django 6.0.7 on 2026-10-01 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0013_alter_livestockinventory_batch'),
        ('production', '0012_productionrecord_valuation_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='slaughter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_output', to='production.slaughterrecord'),
        ),
        migrations.AddField(
            model_name='slaughterrecord',
            name='inventory_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SlaughterAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livestock.livestockinventory')),
                ('slaughter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.slaughterrecord')),
            ],
        ),
        migrations.AddField(
            model_name='slaughterrecord',
            name='selected_animals',
            field=models.ManyToManyField(blank=True, related_name='selected_slaughters', through='production.SlaughterAnimal', to='livestock.livestockinventory'),
        ),
        migrations.AddConstraint(
            model_name='slaughteranimal',
            constraint=models.UniqueConstraint(fields=('slaughter', 'animal'), name='unique_slaughter_animal'),
        ),
    ]
