# Generated by Django 6.0.7 on 2026-10-08 03:07

import django.db.models.deletion
from django.db import migrations, models


def backfill_record_farmer(apps, schema_editor):
    ProductionRecord = apps.get_model("production", "ProductionRecord")
    db = schema_editor.connection.alias
    records = ProductionRecord.objects.using(db).filter(farmer_at_record__isnull=True).select_related(
        "livestock", "batch"
    )
    pending = []
    for record in records.iterator(chunk_size=500):
        if record.livestock_id:
            record.farmer_at_record_id = record.livestock.farmer_id
        elif record.batch_id:
            record.farmer_at_record_id = record.batch.farmer_id
        if record.farmer_at_record_id:
            pending.append(record)
        if len(pending) >= 500:
            ProductionRecord.objects.using(db).bulk_update(pending, ["farmer_at_record"], batch_size=500)
            pending.clear()
    if pending:
        ProductionRecord.objects.using(db).bulk_update(pending, ["farmer_at_record"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0017_livestockownershiptransfer'),
        ('production', '0013_productionrecord_slaughter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='farmer_at_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_records_at_time', to='livestock.farmer'),
        ),
        migrations.RunPython(backfill_record_farmer, migrations.RunPython.noop),
    ]
