# Generated by Django 6.0.6 on 2026-07-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('MAO', 'Municipal Agriculturist Office'), ('SIBAT', 'Sibat'), ('ADMIN', 'Admin')], max_length=20, unique=True),
        ),
    ]
