# Generated by Django 6.0.6 on 2026-07-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('MAO', 'Municipal Agriculturist Office'), ('SIBAT', 'Sibat'), ('ADMIN', 'Admin'), ('AUCTION', 'Auction'), ('SLAUGHTERHOUSESTAFF', 'SlaughterhouseStaff')], max_length=20, unique=True),
        ),
    ]
