# Generated by Django 6.0.7 on 2026-09-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fix_userdocument_approved_by_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('MAO', 'Municipal Agriculturist Office'), ('SIBAT', 'Sibat'), ('AUCTION', 'Auction'), ('SLAUGHTERHOUSESTAFF', 'SlaughterhouseStaff')], max_length=20, unique=True),
        ),
    ]
