# Generated by Django 6.0.7 on 2026-09-29 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(default='General', max_length=40)),
                ('audience', models.CharField(choices=[('ALL', 'Farmers and SIBAT'), ('FARMER', 'Farmers'), ('SIBAT', 'SIBAT')], default='ALL', max_length=10)),
                ('is_published', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('program', models.CharField(max_length=100)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'program'],
            },
        ),
        migrations.CreateModel(
            name='ProgramBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_bookings', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='users.programschedule')),
            ],
            options={
                'ordering': ['schedule__date', 'time'],
            },
        ),
        migrations.AddConstraint(
            model_name='programschedule',
            constraint=models.UniqueConstraint(fields=('date', 'program'), name='unique_program_per_day'),
        ),
        migrations.AddConstraint(
            model_name='programbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('schedule', 'time'), name='unique_confirmed_program_slot'),
        ),
        migrations.AddConstraint(
            model_name='programbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('schedule', 'farmer'), name='unique_farmer_program_booking'),
        ),
    ]
