# Generated by Django 6.0.7 on 2026-09-30 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_announcement_programschedule_programbooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activity_images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='users.programschedule'),
        ),
        migrations.AddField(
            model_name='programschedule',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Vaccination', 'Vaccination'), ('Animal Health', 'Animal Health'), ('Livestock Inspection', 'Livestock Inspection'), ('Disease Prevention', 'Disease Prevention'), ('Farmer Training', 'Farmer Training'), ('Seminar', 'Seminar'), ('Farmer Meeting', 'Farmer Meeting'), ('Livestock Registration', 'Livestock Registration'), ('Field Visit', 'Field Visit'), ('Market / Auction', 'Market / Auction'), ('Livestock Program', 'Livestock Program'), ('Biosecurity Advisory', 'Biosecurity Advisory'), ('Emergency Notice', 'Emergency Notice'), ('Other', 'Other'), ('Health Alert', 'Health Alert'), ('Event', 'Event'), ('Program', 'Program'), ('Market Update', 'Market Update'), ('Field Memo', 'Field Memo')], default='General', max_length=40),
        ),
    ]
