# Generated by Django 6.0.7 on 2026-09-30 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_announcement_image_announcement_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activity_images/%Y/%m/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='programbooking',
            name='unique_confirmed_program_slot',
        ),
        migrations.AddField(
            model_name='programschedule',
            name='capacity',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddConstraint(
            model_name='programschedule',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='program_capacity_at_least_one'),
        ),
        migrations.AddField(
            model_name='announcementphoto',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='users.announcement'),
        ),
    ]
