# Generated by Django 6.0.7 on 2026-10-02 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0014_livestockinventory_individual_inventory_one_head'),
        ('users', '0009_announcementphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_reviewers', to='livestock.barangay'),
        ),
    ]
