# Generated by Django 6.0.7 on 2026-10-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_assigned_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_scope',
            field=models.CharField(choices=[('ASSIGNED_ONLY', 'Assigned barangay'), ('ALL_BARANGAYS', 'All barangays')], default='ASSIGNED_ONLY', max_length=20),
        ),
    ]
