# Generated by Django 6.0.7 on 2026-10-06 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_access_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='review_remarks',
            field=models.TextField(blank=True, default='', help_text='Reason or remarks if returned for revision'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
