# Generated by Django 6.0.7 on 2026-10-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userdocument_review_remarks_userdocument_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_entity_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Primary key of the related model record', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_entity_type',
            field=models.CharField(blank=True, db_index=True, help_text='Entity category for notification lifecycle tracking (e.g. livestock_inventory, inspection)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('disease', 'Disease Surveillance'), ('vaccination', 'Vaccination Schedule'), ('sibat', 'SIBAT Inspection'), ('production', 'Production Milestone'), ('weather', 'Weather Advisory'), ('general', 'General Notice'), ('inspection', 'Livestock Inspection')], default='general', max_length=20),
        ),
    ]
