# Generated by Django 6.0.7 on 2026-10-06 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0015_farmer_rsbsa_number'),
        ('users', '0013_notification_related_entity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_announcements', to='livestock.barangay'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('FARMER_AND_SIBAT', 'Farmer and SIBAT'), ('FARMER_ONLY', 'Farmer Only'), ('SIBAT_ONLY', 'SIBAT Only'), ('ALL', 'All'), ('SIBAT_BARANGAY', 'SIBAT — Their Barangay Only')], default='FARMER_AND_SIBAT', max_length=30),
        ),
    ]
